name: growthbook_sdk_flutter
description: GrowthBook SDK for flutter.
version: 1.0.0+1
homepage: https://github.com/alippo-com/GrowthBook-SDK-Flutter

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dio: ^4.0.6
  enhanced_enum: ^0.1.1
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  tuple: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11

